language: android
sudo: required

android:
  components:
    - tools
    - build-tools-23.0.2
    - android-23
    - extra-android-support
    - extra-google-google_play_services
    - extra-android-m2repository
    - extra-google-m2repository
    - addon-google_apis-google-23

before_install:
 - chmod +x gradlew

after_success:
 - chmod +x ./upload-gh-pages.sh
 - chmod +x ./import-translations-github.sh
 - ./import-translations-github.sh
 - ./upload-gh-pages.sh

script:
 - cd $TRAVIS_BUILD_DIR/
 - ./gradlew assembleDebug
 
notifications:
  slack: glucosio:uk2xb9sAxOaVedj7zePyuBqa
